"""
Patch LiveClassroomPreview.tsx hooks section.
Strategy:
  - No face-api.js (caused SSR crash in Next.js)
  - getUserMedia video (zero lag, native)
  - WebSocket snapshot every 100ms at DISPLAYED resolution
    (applying same object-cover crop Python sees what browser shows)
  - Canvas set to displayed resolution -> Python coords map 1:1, no scaling bugs
"""
import sys

content = open(r'frontend/src/components/dashboard/LiveClassroomPreview.tsx', encoding='utf-8').read()

start = content.find('    const [feedError, setFeedError] = useState(false);')
end   = content.find('    const loadPresenceData = async () => {')

assert start > 0 and end > 0, f"Markers not found: {start}, {end}"

new_block = (
    "    const [camError, setCamError] = useState<string | null>(null);\n"
    "    const cameraActiveTimer = useRef<NodeJS.Timeout | null>(null);\n"
    "\n"
    "    // Camera / canvas refs\n"
    "    const videoRef   = useRef<HTMLVideoElement>(null);\n"
    "    const canvasRef  = useRef<HTMLCanvasElement>(null);\n"
    "    const wsRef      = useRef<WebSocket | null>(null);\n"
    "    const snapRef    = useRef<HTMLCanvasElement | null>(null); // offscreen snap canvas\n"
    "    const sendingRef = useRef(false);\n"
    "    const prevNamesRef = useRef<Set<string>>(new Set());\n"
    "\n"
    "    // Activity Logs\n"
    "    const [activityLogs, setActivityLogs] = useState<ActivityLog[]>([]);\n"
    "\n"
    "    const addActivityLog = useCallback((message: string, type: 'ENTER' | 'LEAVE') => {\n"
    "        const id = Math.random().toString(36).substring(7);\n"
    "        setActivityLogs(prev => [{ id, message, type, timestamp: new Date() }, ...prev].slice(0, 50));\n"
    "    }, []);\n"
    "\n"
    "    // ── Start webcam via getUserMedia ──\n"
    "    const startCamera = useCallback(async () => {\n"
    "        try {\n"
    "            const stream = await navigator.mediaDevices.getUserMedia({\n"
    "                video: { width: { ideal: 1280 }, height: { ideal: 720 }, facingMode: 'user' },\n"
    "                audio: false,\n"
    "            });\n"
    "            const video = videoRef.current;\n"
    "            if (video) {\n"
    "                video.srcObject = stream;\n"
    "                await video.play();\n"
    "                setCameraActive(true);\n"
    "                setCamError(null);\n"
    "            }\n"
    "            snapRef.current = document.createElement('canvas');\n"
    "        } catch {\n"
    "            setCamError('Camera access denied — please allow camera permission and refresh.');\n"
    "        }\n"
    "    }, []);\n"
    "\n"
    "    // ── Draw boxes returned by Python onto the canvas overlay ──\n"
    "    const drawBoxes = useCallback((boxes: { x: number; y: number; w: number; h: number; name: string; conf: number }[]) => {\n"
    "        const canvas = canvasRef.current;\n"
    "        const video  = videoRef.current;\n"
    "        if (!canvas || !video) return;\n"
    "\n"
    "        // Match canvas to the DISPLAYED video rect — no object-cover distortion\n"
    "        const rect = video.getBoundingClientRect();\n"
    "        if (rect.width === 0) return;\n"
    "        canvas.width  = rect.width;\n"
    "        canvas.height = rect.height;\n"
    "\n"
    "        const ctx = canvas.getContext('2d');\n"
    "        if (!ctx) return;\n"
    "        ctx.clearRect(0, 0, canvas.width, canvas.height);\n"
    "\n"
    "        // Snapshot was captured at rect.width x rect.height — boxes are in that same space\n"
    "        boxes.forEach(b => {\n"
    "            const isKnown = !!b.name && b.name !== 'Detecting...';\n"
    "            ctx.strokeStyle = isKnown ? '#22d3ee' : '#f97316';\n"
    "            ctx.lineWidth = 2;\n"
    "            ctx.strokeRect(b.x, b.y, b.w, b.h);\n"
    "\n"
    "            const label = isKnown ? `${b.name}  ${Math.round(b.conf * 100)}%` : 'Detecting...';\n"
    "            ctx.font = 'bold 13px Inter, sans-serif';\n"
    "            const tw = ctx.measureText(label).width;\n"
    "            ctx.fillStyle = isKnown ? 'rgba(34,211,238,0.9)' : 'rgba(249,115,22,0.85)';\n"
    "            ctx.fillRect(b.x, b.y - 22, tw + 10, 22);\n"
    "            ctx.fillStyle = '#000';\n"
    "            ctx.fillText(label, b.x + 5, b.y - 5);\n"
    "        });\n"
    "    }, []);\n"
    "\n"
    "    // ── WebSocket: send snapshot → Python face recognition → draw boxes ──\n"
    "    useEffect(() => {\n"
    "        let ws: WebSocket;\n"
    "        let interval: ReturnType<typeof setInterval>;\n"
    "\n"
    "        const capture = () => {\n"
    "            const video = videoRef.current;\n"
    "            const snap  = snapRef.current;\n"
    "            if (!video || !snap || video.readyState < 4 || video.paused || sendingRef.current) return;\n"
    "            if (!ws || ws.readyState !== WebSocket.OPEN) return;\n"
    "\n"
    "            // Capture at displayed resolution with correct object-cover crop\n"
    "            const rect = video.getBoundingClientRect();\n"
    "            const dW = rect.width || 640;\n"
    "            const dH = rect.height || 360;\n"
    "            const nW = video.videoWidth  || dW;\n"
    "            const nH = video.videoHeight || dH;\n"
    "\n"
    "            // Compute what object-cover would crop/scale\n"
    "            const scale = Math.max(dW / nW, dH / nH);\n"
    "            const srcW  = dW / scale;  // visible native width\n"
    "            const srcH  = dH / scale;  // visible native height\n"
    "            const srcX  = (nW - srcW) / 2;\n"
    "            const srcY  = (nH - srcH) / 2;\n"
    "\n"
    "            snap.width  = dW;\n"
    "            snap.height = dH;\n"
    "            const ctx = snap.getContext('2d');\n"
    "            if (!ctx) return;\n"
    "            // Draw only the visible portion of the video (matches object-cover display)\n"
    "            ctx.drawImage(video, srcX, srcY, srcW, srcH, 0, 0, dW, dH);\n"
    "\n"
    "            sendingRef.current = true;\n"
    "            snap.toBlob(blob => {\n"
    "                if (blob && ws.readyState === WebSocket.OPEN) ws.send(blob);\n"
    "                sendingRef.current = false;\n"
    "            }, 'image/jpeg', 0.8);\n"
    "        };\n"
    "\n"
    "        const connect = () => {\n"
    "            ws = new WebSocket('ws://localhost:5000');\n"
    "            wsRef.current = ws;\n"
    "\n"
    "            ws.onopen  = () => { interval = setInterval(capture, 120); };\n"
    "\n"
    "            ws.onmessage = (evt) => {\n"
    "                try {\n"
    "                    const data  = JSON.parse(evt.data);\n"
    "                    const boxes = (data.boxes || []) as { x: number; y: number; w: number; h: number; name: string; conf: number }[];\n"
    "                    drawBoxes(boxes);\n"
    "\n"
    "                    // Immediate ENTER / LEAVE activity log\n"
    "                    const currentNames = new Set<string>(\n"
    "                        boxes.filter(b => b.name && b.name !== 'Detecting...').map(b => b.name)\n"
    "                    );\n"
    "                    prevNamesRef.current.forEach(name => {\n"
    "                        if (!currentNames.has(name)) addActivityLog(`${name} left camera view`, 'LEAVE');\n"
    "                    });\n"
    "                    currentNames.forEach(name => {\n"
    "                        if (!prevNamesRef.current.has(name)) addActivityLog(`${name} entered camera view`, 'ENTER');\n"
    "                    });\n"
    "                    prevNamesRef.current = currentNames;\n"
    "                } catch {}\n"
    "            };\n"
    "\n"
    "            ws.onclose = () => { clearInterval(interval); setTimeout(connect, 3000); };\n"
    "        };\n"
    "\n"
    "        connect();\n"
    "        return () => { clearInterval(interval); ws?.close(); };\n"
    "    }, [drawBoxes, addActivityLog]);\n"
    "\n"
)

new_content = content[:start] + new_block + content[end:]
open(r'frontend/src/components/dashboard/LiveClassroomPreview.tsx', 'w', encoding='utf-8').write(new_content)
print(f'Done. File is {len(new_content)} bytes.')
print(f'New block: {len(new_block)} bytes replacing {end - start} bytes.')
